name: Trigger auto deployment for todo-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'src/**'
    - '.github/workflows/todo-api-AutoDeployTrigger-155aebde-23f2-487b-b8b9-38dc62d2f2d7.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: mvpcontainerregister.azurecr.io
          username: ${{ secrets.TODOAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.TODOAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mvpcontainerregister.azurecr.io/todo-api:${{ github.sha }}
          file: ./src/Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TODOAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n todo-api -g mvp-data-sync --server mvpcontainerregister.azurecr.io --username  ${{ secrets.TODOAPI_REGISTRY_USERNAME }} --password ${{ secrets.TODOAPI_REGISTRY_PASSWORD }}
            az containerapp update -n todo-api -g mvp-data-sync --image mvpcontainerregister.azurecr.io/todo-api:${{ github.sha }}
